# -*- coding: utf-8 -*-
"""annotate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfzYvQEZAhZbIZg-LTEgtBqBnnHa3v9W
"""

import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [10, 20, 15, 25, 30]
plt.plot(x, y, marker='o')
# Add title and labels
plt.title("Text and Annotation Example")
plt.xlabel("X Values")
plt.ylabel("Y Values")
# Add text
plt.text(2, 22, "Sample Text", fontsize=12, color='blue')
# Add annotation
plt.annotate(
    'Highest Point',
    xy=(5, 30),
    xytext=(3, 35),
    arrowprops=dict(facecolor='black', shrink=0.05)
)
plt.grid(True)
plt.show()